# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the feature/v3 branch
on:
  push:
    branches: [ feature/v3 ]
  pull_request:
    branches: [ feature/v3 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.0.100

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 13.x
        check-latest: true
        
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: npm ci
      working-directory: ${{ github.workspace }}/autorest.azure-functions-csharp
